### ISSUE TITLE
Add support for Tekton's beta CustomRun

### ISSUE THREAD

**Issue by SaschaSchwarze0** [shipwright-io/triggers#24]
We support so far Tekton's alpha Run. In the meantime, Tekton also has a beta version called CustomRun. A feature flag on Tekton controls which of the two CRDs are used by Tekton. Since v0.44.0, the beta CustomRun is default. Reference: https://github.com/tektoncd/pipeline/blob/v0.44.0/config/config-feature-flags.yaml#L96

We should provide conditional support based on the availability of the custom resource definition.

**Comment by otaviof** [comment]
We might need to [watch for both objects in the controller](https://github.com/shipwright-io/triggers/blob/00e4b4558f931b7895d73a3dc1ff00dce1c07c21/controllers/customtasks_controller.go#L230-L231), also make sure the golang "vendoring" is reflecting what we need.

**Comment by SaschaSchwarze0** [comment]
> We might need to [watch for both objects in the controller](https://github.com/shipwright-io/triggers/blob/00e4b4558f931b7895d73a3dc1ff00dce1c07c21/controllers/customtasks_controller.go#L230-L231), also make sure the golang "vendoring" is reflecting what we need.

+1 I think the CustomRun does not exist in Tekton v0.38 yet = we need a bump of the Tekton version. And if we do that as usual, then we would do that in the Build repo and then pick up that change in Triggers.
